apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler 
metadata:
  name: web-autoscaling 
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1 
    kind: deployment 
    name: web-deployment
  targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler 
metadata:
  name: tomcat-autoscaling 
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1 
    kind: deployment 
    name: tomcat-deployment
  targetCPUUtilizationPercentage: 50