apiVersion: apps/v1
kind: Deployment 
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: db 
  template:
    metadata:
      labels:
        name: db 
    spec:
      containers:
        - name: db-container
          image: mysql 
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD #secret에서 참조
              valueFrom:
                secretKeyRef:
                  name: db-sceret
                  key: root_password
          volumeMounts:
            - name:  db-storage 
              mountPath: /var/lib/mysql
      volumes: #pv에서 저장공간 할당
        - name: db-storage 
          persistentVolumeClaim:
            claimName: mypvc
