apiVersion: v1
kind: Service
metadata:
  name: tomcat-svc # 이전에 작성했던 workers.properties
                   # 파일에서 명시한 host에 적은 이름(주소)과 같아야함.
                   # 쿠버네티스는 클러스터 내에서 파드 이름이나 서비스 이름이
                   # DNS 주소처럼 쓰일 수 있음.
spec:
  selector:
    name: tomcat
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: tom
      port: 8009
      targetPort: 8009
      
    