apiVersion: v1
kind: PersistentVolume 
metadata:
  name: mypv
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 192.168.10.50 # nfs-server 주소
    path: "/db"
---
apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: mypvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi 
 
